server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mooc?characterEncoding=utf-8&useSSL=false
    username: root
    password: xie.159753.
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.buaa.moocserver.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql